version: 2.1
orbs:
  slack: circleci/slack@4.3.0
  aws-cli: circleci/aws-cli@1.3.0
commands:
  slack-notification-fail:
    description: Send notification to Slack
    steps:
      - slack/notify:
          channel: C01Q98F10H2
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": "Your job *$CIRCLE_JOB* has *faild* :octagonal_sign: (<$CIRCLE_BUILD_URL|build #$CIRCLE_BUILD_NUM>)\n\nrepo: $CIRCLE_REPOSITORY_URL\n\nbranch: $CIRCLE_BRANCH\n\ncommitter: $CIRCLE_USERNAME"
                  }
                }
              ]
            }
  slack-notification-pass:
    description: Send notification to Slack
    steps:
      - slack/notify:
          channel: C01Q98F10H2
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": "Your job *$CIRCLE_JOB* has *built* :white_check_mark: (<$CIRCLE_BUILD_URL|build #$CIRCLE_BUILD_NUM>)\n\nrepo: $CIRCLE_REPOSITORY_URL\n\nbranch: $CIRCLE_BRANCH\n\ncommitter: $CIRCLE_USERNAME"
                  }
                }
              ]
            }
jobs:
  setup-environment:
    docker:
      - image: circleci/node:12.16-browsers
    working_directory:  ~/frontend
    steps:
      - checkout
          path: ~/frontend
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Install prerequsites
          command: |
            sudo apt -y install git curl
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
         # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
          # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

  test-frontend:
    docker:
      - image: circleci/node:12.16-browsers
    working_directory: ~/frontend
    steps:
      - checkout
        path: ~/frontend
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Run frontend tests
          command: |
            npm run test
      - slack-notification-fail
  scan-frontend:
    docker:
      - image: circleci/node:12.16-browsers
    working_directory: ~/frontend
    steps:
      - checkout
        path: ~/frontend
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: lint frontend
          command: |
            cd frontend
            npm run lint
      - run:
          name: Scan frontend security
          command: |
            cd frontend
            npm audit --audit-level=critical
      - slack-notification-fail
  build-frontend:
    docker:
      - image: circleci/node:12.16-browsers
    working_directory: ~/frontend
    steps:
      - checkout
        path: ~/frontend
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Build front-end
          command: |
            npm run build
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
      - slack-notification-fail
  deploy-frontend:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - aws-cli/setup
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            cd frontend
            sudo apt -y install jq tar gzip git curl
            npm install -g @angular/cli
            npm install
      - run:
          name: Build frontend
          command: |
            cd frontend
            npm run build
      - run:
          name: build a docker container
          command: |
            docker build --tag=ramyaperi/dev:devops-"${CIRCLE_WORKFLOW_ID:0:7}" .
      - run:
          name: push a docker container
          command: |
            docker push ramyaperi/dev:devops-"${CIRCLE_WORKFLOW_ID:0:7}"
      - slack-notification-fail
workflows:
  default:
    jobs:
      - setup-environment:
          context: slack
      - test-frontend:
          context: slack
          requires: [setup-environment]
      - scan-frontend:
          context: slack
          requires: [setup-environment]
      - build-frontend:
          context: slack
          requires:
            - setup-environment
            - test-frontend
            - scan-frontend
