version: 2.1
orbs:
  slack: circleci/slack@4.3.0
  aws-cli: circleci/aws-cli@1.3.0
  angular: okode/angular@1.0.137
commands:
  slack-notification-fail:
    description: Send notification to Slack
    steps:
      - slack/notify:
          channel: C01Q98F10H2
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": "Your job *$CIRCLE_JOB* has *faild* :octagonal_sign: (<$CIRCLE_BUILD_URL|build #$CIRCLE_BUILD_NUM>)\n\nrepo: $CIRCLE_REPOSITORY_URL\n\nbranch: $CIRCLE_BRANCH\n\ncommitter: $CIRCLE_USERNAME"
                  }
                }
              ]
            }
  slack-notification-pass:
    description: Send notification to Slack
    steps:
      - slack/notify:
          channel: C01Q98F10H2
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": "Your job *$CIRCLE_JOB* has *built* :white_check_mark: (<$CIRCLE_BUILD_URL|build #$CIRCLE_BUILD_NUM>)\n\nrepo: $CIRCLE_REPOSITORY_URL\n\nbranch: $CIRCLE_BRANCH\n\ncommitter: $CIRCLE_USERNAME"
                  }
                }
              ]
            }
jobs:
  setup-environment:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install prerequsites
          command: |
            sudo apt -y install git curl
      - run:
          name: set up front-end
          command: |
            cd frontend
            sudo su
            npm i
      - save_cache:
          paths: [ frontend ]
          key: frontend-build
  build-frontend:
    executor: common/node
    steps:
      - checkout
      - node/install-packages
      - restore_cache:
          keys: [ frontend ]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm run build
      - save_cache:
          paths: [ frontend ]
          key: frontend-build
      - slack-notification-fail
  test-frontend:
    executor: common/node-browsers
    steps:
      - checkout
      - common/chrome-upgrade
      - restore_cache:
          keys: [ frontend ]
      - run:
          name: Run frontend tests
          command: |
            cd frontend
            npm run test
      - slack-notification-fail
  scan-frontend:
    executor: common/node
    steps:
      - checkout
      - restore_cache:
          keys: [ frontend ]
      - run:
          name: lint frontend
          command: |
            cd frontend
            npm run lint
      - run:
          name: Scan frontend security
          command: |
            cd frontend
            npm audit --audit-level=critical
      - slack-notification-fail
  deploy-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - aws-cli/setup
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            cd frontend
            sudo apt -y install jq tar gzip git curl
            npm install -g @angular/cli
            npm install
      - run:
          name: Build frontend
          command: |
            cd frontend
            npm run build
      - run:
          name: build a docker container
          command: |
            docker build --tag=ramyaperi/dev:devops-"${CIRCLE_WORKFLOW_ID:0:7}" .
      - run:
          name: push a docker container
          command: |
            docker push ramyaperi/dev:devops-"${CIRCLE_WORKFLOW_ID:0:7}"
      - slack-notification-fail
workflows:
  default:
    jobs:

      - test-frontend:
          context:
            - slack
            - angular

      - scan-frontend:
          context:
            - slack
            - angular

      - build-frontend:
          context:
            - slack
            - angular
          requires:
            - test-frontend
            - scan-frontend
