Description:
   udacity capstone  Project
  want to create a server  with kubernetes cluster

Parameters:
  EnvironmentName:
    Description: An environment name
    Type: String

Resources:
  UdaCapRolIAM:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvironmentName}-UdaCap-Role"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"

  UdaCapPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${EnvironmentName}-UdaCap-Policies"
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - "ec2:DescribeAddresses"
              - "ec2:AllocateAddress"
              - "ec2:DescribeInstances"
              - "ec2:AssociateAddress"
              - "ssm:Get*"
              - "s3:Get*"
            Resource: '*'
      Roles:
        - !Ref UdaCapRolIAM

  UdaCapInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - !Ref UdaCapRolIAM

  LoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our load balancer
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: name
          Value: !Sub ${EnvironmentName} SecGroup of Load Balancer

  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          #needed so for updating and installing docker and others
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0767046d1677be5a0
      InstanceType: t2.medium
      KeyName: udacapstone
      SecurityGroupIds:
        - !Ref WebServerSecGroup
      SubnetId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-PUB1-SN"
      UserData:
        Fn::Base64: !Sub |
            sudo apt-get update &amp;&amp; sudo apt-get install -y apt-transport-https
            curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
            sudo apt-get update
            sudo apt-get install -y kubectl
            sudo apt-get install docker.io
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube
            sudo mv minikube /usr/local/bin
            sudo apt-get install -y conntrack
            minikube addons enable ingress
Outputs:
  EC2DSN:
    Description: public DNS for the ec2 instance
    Value: !Join
      - ''
      - - ''
        - !GetAtt
          - EC2Instance
          - PublicDnsName
